# autogenerated by txs
#include:expl3
#include:xparse
\DeclareBabelToExplLanguageMapping{arg1}#S
\DeclareCaseLangs#S
\DeclareCaseLangs*#S
\MakeCapital{arg1}#S
\MakeSentenceCase#S
\MakeSentenceCase*#S
\UndeclareBabelToExplLanguageMapping{arg1}#S
\ifcaselang#S
\ifcaselang[optarg1]#S
